### ISSUE TITLE
OpenPnPCaptureCamera does not re-select proper CaptureFormat in Combobox

### ISSUE THREAD

**Issue by markmaker** [openpnp/openpnp-capture-java#4]
# Description

When switching between Camera Wizards, the Format Combobox is not properly set. The Format always reverts to the first item in the list. 

![grafik](https://user-images.githubusercontent.com/9963310/91100941-5c6e3300-e666-11ea-80c1-b82e8f8d7879.png)

This is due to some sort of race condition, i.e. it suddenly started happening. 

# Diagnosis

Combobox items are selected by calling `equals()` on the items and the selection. The bug happens, because the `equals()` override on the `CaptureFormat` defers to `CapFormatInfo` here:

https://github.com/openpnp/openpnp-capture-java/blob/f7c75326702778aaede54eaa2e963b7f62f971fa/src/main/java/org/openpnp/capture/CaptureFormat.java#L39

`CapFormatInfo` in turn inherits from `com.sun.jna.Structure`, where `equals()` is implemented as follows:

![grafik](https://user-images.githubusercontent.com/9963310/91101376-35fcc780-e667-11ea-845f-e57830ec345c.png)

The structure is compared by pointer of the structure. 

This is obviously wrong, because the structure was obtained by copy through `org.openpnp.capture.library.OpenpnpCaptureLibrary.Cap_getFormatInfo(Pointer, int, int, CapFormatInfo)`. 

https://github.com/openpnp/openpnp-capture-java/blob/f7c75326702778aaede54eaa2e963b7f62f971fa/src/main/java/org/openpnp/capture/CaptureDevice.java#L27-L32

I suspect that Java will move these around on Garbage Collect or whatever. It started happening once I added my 720p 120fps Camera. 

This is the debugger view:
![grafik](https://user-images.githubusercontent.com/9963310/91103333-8fff8c00-e66b-11ea-98cf-e4ca97e55948.png)
Although the format is clearly the same, it compares as `false`.

# Possible Fix

Rewrite `equals() `to compare the properties of `formatInfo` or simply compare `formatId` as it is XML-persisted by that ordinal number anyway. 

`Unfortunately I don't know how to compile and test openpnp-capture-java.

**Comment by markmaker** [comment]
Hi @vonnieda 

Could you please have a look here? This really bugs me. 

Thanks!

_Mark

**Comment by vonnieda** [comment]
@markmaker Can you check that you are on the latest develop, especially including https://github.com/openpnp/openpnp/commit/e1f6010d57045353cbfd005cf1f1c4299a82171f? We debugged this issue on Discord the other day and that change seemed to be what caused it.

**Comment by markmaker** [comment]
Thanks for the quick answer.

No I'm on `test`.

![grafik](https://user-images.githubusercontent.com/9963310/91103545-056b5c80-e66c-11ea-81b2-3b5a61be3f89.png)

But IMHO this comparison by pointer is wrong anyway.

_Mark

**Comment by markmaker** [comment]
Btw. I've updated the description.

**Comment by markmaker** [comment]
Well, I have to go to bed now... 
  B-]

**Comment by ian-arkver** [comment]
Hi Mark,

I thought you'd already backed out GstreamerCamera on your tree. I recall you mentioned some other problem with it.

The problem here isn't really with GstreamerCamera but with the updated JNA that's pulled in by the org.freedesktop.gstreamer dependency. Something in there isn't compatible with the older JNA used by OpenPnPCapture's java bindings. I think your detailed problem diagnosis in the description here has pointed at the exact problem.

It's possible that compiling OpenPnPCapture with the new JNA would sort this, but that's not easily doable with the jnaerator used to create the bindings. It's also possible that fixing up equals() as you describe would fix it, which would be nice.

I tried and failed to compile up openpnpcapture to fix this since I think the fix requires the jnaerated bindings to be frozen and jnaerator removed from the build and replaced with an explicit dependency on the newer jna.

Regards,
Ian

**Comment by markmaker** [comment]
>  thought you'd already backed out GstreamerCamera on your tree. I recall you mentioned some other problem with it.

No, I just deleted the GstreamerCamera from the `machine.xml` you gave me, as it wouldn't load correctly on Windows 10. 

@vonnieda can I just merge develop into test? This way it would also catch up with stuff merged since. But how exactly must the merge be done?

I'm really unsure how git works, when reverted/squashed/rebased merges are merged again. In theory, it's all logical, but in practice it never seems to do what I expect. In my own company I have forbidden any squashing/rebasing. 

_Mark

**Comment by vonnieda** [comment]
@markmaker To be clear, the error was introduced back in April and reverted the other day. If you sync up to develop this problem should go away.

For what it's worth, I don't bother with rebasing because I find it overly complex. I just merge back from the main branch after a PR is merged and it works fine. It does create extra merge commits in the history, but that's okay with me.

So, for the process looks like:

1. Commit to `mark/feature`.
2. Merge (pull) `mark/feature` into `openpnp/develop`.
3. Merge (pull) `openpnp/develop` into `mark/feature` if you want to keep working on that feature, or merge (pull) `openpnp/develop` into `mark/develop` and make a new `mark/feature` branch.

**Comment by vonnieda** [comment]
@markmaker Can you try latest test and see if this is resolved?

**Comment by markmaker** [comment]
Frankly, I can't really remember how this got resolved then. However, I never observed that issue anymore and I'm confident I would have noticed.

_Mark
